import Foundation
import XCTest
@testable import KlimaCore

/// Shared fixtures of the place tests: the shipped App/Resources/places.bin + localities.bin (indexed once per test
/// run), the goldens generated by scripts/places_reference.py and trimmed Scotty LocMatch/LocGeoPos responses.
enum PlaceFixtures {
    static let testsDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
    static let repoRoot = testsDir.deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        .deletingLastPathComponent()
    static let resources = repoRoot.appendingPathComponent("App/Resources")
    static let placesURL = resources.appendingPathComponent("places.bin")
    static let localitiesURL = resources.appendingPathComponent("localities.bin")
    /// The ODbL layer (lines and tags from OpenStreetMap), loaded like the app does (`PlaceIndexLoader(bundle:)`).
    static let osmURL = resources.appendingPathComponent("stops_osm.bin")
    static let dir = testsDir.appendingPathComponent("Fixtures/places")

    /// Full offline index with the OSM layer, as in the app (built once; ~5 s in a debug build).
    static let index: PlaceIndex = {
        do {
            return try PlaceIndex(placesURL: placesURL, localitiesURL: localitiesURL, osmURL: osmURL)
        } catch {
            fatalError("cannot load \(placesURL.path): \(error)")
        }
    }()

    static let dataset: PlaceDataset = {
        do { return try PlaceDataset(placesURL: placesURL, localitiesURL: localitiesURL) } catch { fatalError("\(error)") }
    }()

    static func json(_ name: String) -> Any {
        let url = dir.appendingPathComponent(name)
        guard let data = try? Data(contentsOf: url), let obj = try? JSONSerialization.jsonObject(with: data) else {
            fatalError("missing fixture \(url.path)")
        }
        return obj
    }

    static func liveData(_ scenario: String) -> Data {
        let url = dir.appendingPathComponent("live/\(scenario).json")
        guard let data = try? Data(contentsOf: url) else { fatalError("missing live fixture \(url.path)") }
        return data
    }

    static func live(_ scenario: String) -> [Place] { LocMatchDecoder.places(fromResponse: liveData(scenario)) }

    static let golden: [String: Any] = json("golden_places.json") as! [String: Any]

    /// Golden row notation: "S:" stop/station, "Ort:" locality, "A:" address, "P:" POI.
    static func fmt(_ p: Place) -> String {
        switch p.kind {
        case .station, .stop: return "S:" + p.name
        case .town: return "Ort:" + p.name
        case .address: return "A:" + p.name
        case .poi: return "P:" + p.name
        }
    }

    static func record(named name: String, kind: PlaceKind? = nil) -> Place? {
        guard let ri = index.table.recs.firstIndex(where: { $0.name == name && (kind == nil || $0.kind == kind) }) else { return nil }
        return index.place(ri)
    }

    static func context(_ c: [String: Any]) -> PlaceSearchContext {
        var ctx = PlaceSearchContext(mode: (c["mode"] as? String) == "tripLog" ? .tripLog : .planner)
        if let near = c["near"] as? [Double] { ctx.near = GeoPoint(latitude: near[0], longitude: near[1]) }
        if let favs = c["favourites"] as? [String] { ctx.favourites = Set(favs) }
        if let rec = c["recents"] as? [String: [String: Any]] {
            for (id, v) in rec {
                ctx.recents[id] = PlaceRecentUse(ageDays: (v["ageDays"] as? NSNumber)?.doubleValue ?? 0,
                                                 uses: (v["uses"] as? NSNumber)?.intValue ?? 0)
            }
        }
        return ctx
    }
}
